// <auto-generated />
namespace ItPedia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2016_02_09_17_13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2016_02_09_17_13));
        
        string IMigrationMetadata.Id
        {
            get { return "201602091513416_2016_02_09_17_13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
